-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 11:12:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SuperBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SuperBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuperBase` DEFAULT CHARACTER SET utf8 ;
USE `SuperBase` ;

-- -----------------------------------------------------
-- Table `SuperBase`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperBase`.`tb_produtos` (
  `IDProdutos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NomeProduto` VARCHAR(100) NOT NULL,
  `QuantidadeProduto` INT NULL,
  `CustoProduto` DECIMAL UNSIGNED NOT NULL,
  `VendaProduto` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`IDProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperBase`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperBase`.`tb_pedidos` (
  `IDPedidos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DataPedido` DATE NOT NULL,
  `Funcionario` VARCHAR(100) NOT NULL,
  `IDProdutoPedido` INT UNSIGNED NOT NULL,
  `ValorPedido` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`IDPedidos`),
  INDEX `fk_tb_pedidos_tb_produtos_idx` (`IDProdutoPedido` ASC),
  CONSTRAINT `fk_tb_pedidos_tb_produtos`
    FOREIGN KEY (`IDProdutoPedido`)
    REFERENCES `SuperBase`.`tb_produtos` (`IDProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperBase`.`tb_composto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperBase`.`tb_composto` (
  `IDComposto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `VendaComposto` DECIMAL NOT NULL,
  `IDItem` INT UNSIGNED NOT NULL,
  `CustoComposto` DECIMAL NOT NULL,
  PRIMARY KEY (`IDComposto`),
  INDEX `fk_tb_composto_tb_produtos1_idx` (`IDItem` ASC),
  CONSTRAINT `fk_tb_composto_tb_produtos1`
    FOREIGN KEY (`IDItem`)
    REFERENCES `SuperBase`.`tb_produtos` (`IDProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperBase`.`tb_geral_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperBase`.`tb_geral_produtos` (
  `IDGeral` INT UNSIGNED NOT NULL,
  `Custo` DECIMAL NOT NULL,
  PRIMARY KEY (`IDGeral`),
  CONSTRAINT `fk_tb_geral_produtos_tb_composto1`
    FOREIGN KEY (`IDGeral`)
    REFERENCES `SuperBase`.`tb_composto` (`IDComposto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_geral_produtos_tb_produtos1`
    FOREIGN KEY (`IDGeral`)
    REFERENCES `SuperBase`.`tb_produtos` (`IDProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
